[project]
name = "passmanager"
version = "0.1.0"
description = "Python aiobot for managing passwords"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.25.0",
    "cryptography>=46.0.5",
    "loguru>=0.7.3",
    "orjson>=3.11.7",
    "pyyaml>=6.0.3",
    "ruff>=0.15.1",
    "uvloop>=0.22.1",
]

[tool.ruff]
unsafe-fixes = true
line-length = 88
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "W",
    "F",
    "Q",
    "I",
    "UP",
    "PERF",
    "ASYNC",
    "C4",
    "ISC",
    "RET",
    "FURB",
]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
